import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import gpuData from '../../data/gpus.json';
import { getProfilesForGpu } from '../../engines/densityEngine';
import { useConfigStore } from '../../store/configStore';
import type { GpuCard } from '../../types/gpu';

function generateConfigSnippet(gpu: GpuCard, selectedSeries: string[]): string {
  const filter =
    selectedSeries.length > 0
      ? (selectedSeries as ('Q' | 'B' | 'A' | 'C')[])
      : undefined;
  const profiles = getProfilesForGpu(gpu, filter);

  const lines = [
    `# Horizon graphic-profiles.properties for ${gpu.model}`,
    '# Generated by vGPU Advisor — https://fjacquet.github.io/vgpu-advisor/',
    '# Add these entries to: %SYSTEMDRIVE%\\ProgramData\\VMware\\VDM\\conf\\graphic-profiles.properties',
    '#',
    `# GPU: ${gpu.model} (${gpu.architecture}, ${gpu.vram_gb}GB, ${gpu.slot_width === 1 ? 'Single' : 'Double'}-Width)`,
    '',
    ...profiles.map((p) => `${p.horizonString}.name=${p.horizonString}`),
    '',
    '# Display capabilities per series:',
    '# Q (vWS): max 4 displays, 8K, 60fps — requires NVIDIA vWS license',
    '# B (vPC): max 2 displays, 45fps — requires NVIDIA vPC license',
    '# A (vCS): max 1 display, compute-optimized — requires NVIDIA vCS license',
    '# C (Compute): headless compute only — requires NVIDIA vCS license',
  ];

  return lines.join('\n');
}

export function HorizonConfigSnippet() {
  const { t } = useTranslation();
  const { selectedGpuId, selectedSeries } = useConfigStore();
  const [copied, setCopied] = useState(false);

  const gpus = gpuData as GpuCard[];
  const selectedGpu = gpus.find((g) => g.id === selectedGpuId);

  if (!selectedGpu) {
    return (
      <div className="flex flex-col items-center justify-center h-48 text-gray-400 dark:text-gray-500 text-sm">
        <p>{t('config.noGpu')}</p>
      </div>
    );
  }

  const snippet = generateConfigSnippet(selectedGpu, selectedSeries);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(snippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-3">
      <p className="text-sm text-gray-600 dark:text-gray-400">
        {t('config.description')}
      </p>

      <div className="relative">
        <button
          type="button"
          onClick={handleCopy}
          className="absolute top-2 right-2 inline-flex items-center gap-1 px-2 py-1 text-xs rounded bg-gray-700 hover:bg-gray-600 text-gray-200 transition-colors"
        >
          {copied ? (
            <>
              <svg
                className="w-3 h-3 text-green-400"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg
                className="w-3 h-3"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                />
              </svg>
              {t('config.copy')}
            </>
          )}
        </button>
        <pre className="text-xs font-mono bg-gray-900 dark:bg-gray-950 text-gray-100 rounded-lg p-4 overflow-x-auto whitespace-pre-wrap leading-relaxed">
          {snippet}
        </pre>
      </div>
    </div>
  );
}
