import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import gpuData from '../../data/gpus.json';
import { getProfilesForGpu } from '../../engines/densityEngine';
import { useConfigStore } from '../../store/configStore';
import type { GpuCard, VgpuProfile } from '../../types/gpu';

type Platform = 'horizon' | 'citrix';

function toXenServerTypeName(gpu: GpuCard, profile: VgpuProfile): string {
  const gpuName = gpu.model.replace(/^NVIDIA\s+/i, '');
  return `GRID ${gpuName}-${profile.vram_gb}${profile.series}`;
}

function generateHorizonSnippet(
  gpu: GpuCard,
  selectedSeries: string[]
): string {
  const filter =
    selectedSeries.length > 0
      ? (selectedSeries as ('Q' | 'B' | 'A' | 'C')[])
      : undefined;
  const profiles = getProfilesForGpu(gpu, filter);

  const lines = [
    `# Horizon graphic-profiles.properties for ${gpu.model}`,
    '# Generated by vGPU Advisor — https://fjacquet.github.io/vgpu-advisor/',
    '# Add these entries to: %SYSTEMDRIVE%\\ProgramData\\VMware\\VDM\\conf\\graphic-profiles.properties',
    '#',
    `# GPU: ${gpu.model} (${gpu.architecture}, ${gpu.vram_gb}GB, ${gpu.slot_width === 1 ? 'Single' : 'Double'}-Width)`,
    '',
    ...profiles.map((p) => `${p.horizonString}.name=${p.horizonString}`),
    '',
    '# Display capabilities per series:',
    '# Q (vWS): max 4 displays, 8K, 60fps — requires NVIDIA vWS license',
    '# B (vPC): max 2 displays, 45fps — requires NVIDIA vPC license',
    '# A (vCS): max 1 display, compute-optimized — requires NVIDIA vCS license',
    '# C (Compute): headless compute only — requires NVIDIA vCS license',
  ];

  return lines.join('\n');
}

function generateCitrixSnippet(gpu: GpuCard, selectedSeries: string[]): string {
  const filter =
    selectedSeries.length > 0
      ? (selectedSeries as ('Q' | 'B' | 'A' | 'C')[])
      : undefined;
  const profiles = getProfilesForGpu(gpu, filter);
  const vramPerGpu = gpu.vram_gb / gpu.gpu_count_per_card;

  const profileBlocks = profiles.map((p) => {
    const xenName = toXenServerTypeName(gpu, p);
    const maxVms = Math.floor(vramPerGpu / p.vram_gb);
    return [
      `# Profile: ${xenName}  (Horizon: ${p.horizonString}) — ${p.vram_gb} GB, max ${maxVms} VMs/GPU`,
      `VGPU_TYPE=$(xe vgpu-type-list model-name="${xenName}" params=uuid --minimal)`,
      'xe vgpu-create vm-uuid=<VM-UUID> gpu-group-uuid=<GPU-GROUP-UUID> vgpu-type-uuid=$VGPU_TYPE',
    ].join('\n');
  });

  const lines = [
    `# XenServer / XCP-ng vGPU configuration for ${gpu.model}`,
    '# Generated by vGPU Advisor — https://fjacquet.github.io/vgpu-advisor/',
    '# Profile names are IDENTICAL to Horizon. On XenServer, vGPU is assigned per-VM.',
    '#',
    `# GPU: ${gpu.model} (${gpu.architecture}, ${gpu.vram_gb}GB)`,
    '',
    '# Step 1 — list GPU groups (one per physical GPU or card):',
    'xe gpu-group-list',
    '',
    '# Step 2 — for each desired profile, get the vGPU type UUID and assign to VM:',
    '',
    ...profileBlocks.flatMap((b) => [b, '']),
    '# Note: Same NVIDIA vGPU licenses apply (vWS/vPC/vCS).',
    '# For Citrix CVAD on vSphere: assign the vGPU profile via vCenter VM hardware settings — no xe commands needed.',
  ];

  return lines.join('\n');
}

export function HorizonConfigSnippet() {
  const { t } = useTranslation();
  const { selectedGpuId, selectedSeries } = useConfigStore();
  const [copied, setCopied] = useState(false);
  const [platform, setPlatform] = useState<Platform>('horizon');

  const gpus = gpuData as GpuCard[];
  const selectedGpu = gpus.find((g) => g.id === selectedGpuId);

  if (!selectedGpu) {
    return (
      <div className="flex flex-col items-center justify-center h-48 text-gray-400 dark:text-gray-500 text-sm">
        <p>{t('config.noGpu')}</p>
      </div>
    );
  }

  const snippet =
    platform === 'horizon'
      ? generateHorizonSnippet(selectedGpu, selectedSeries)
      : generateCitrixSnippet(selectedGpu, selectedSeries);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(snippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-3">
      {/* Platform toggle */}
      <div className="flex items-center gap-1 p-1 bg-gray-100 dark:bg-gray-800 rounded-lg w-fit">
        <button
          type="button"
          onClick={() => setPlatform('horizon')}
          className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${
            platform === 'horizon'
              ? 'bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 shadow-sm'
              : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
          }`}
        >
          {t('config.platformHorizon')}
        </button>
        <button
          type="button"
          onClick={() => setPlatform('citrix')}
          className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${
            platform === 'citrix'
              ? 'bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 shadow-sm'
              : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
          }`}
        >
          {t('config.platformCitrix')}
        </button>
      </div>

      <p className="text-sm text-gray-600 dark:text-gray-400">
        {platform === 'horizon'
          ? t('config.description')
          : t('config.citrixDescription')}
      </p>

      <div className="relative">
        <button
          type="button"
          onClick={handleCopy}
          className="absolute top-2 right-2 inline-flex items-center gap-1 px-2 py-1 text-xs rounded bg-gray-700 hover:bg-gray-600 text-gray-200 transition-colors"
        >
          {copied ? (
            <>
              <svg
                className="w-3 h-3 text-green-400"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg
                className="w-3 h-3"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                />
              </svg>
              {t('config.copy')}
            </>
          )}
        </button>
        <pre className="text-xs font-mono bg-gray-900 dark:bg-gray-950 text-gray-100 rounded-lg p-4 overflow-x-auto whitespace-pre-wrap leading-relaxed">
          {snippet}
        </pre>
      </div>
    </div>
  );
}
