import { useTranslation } from 'react-i18next';
import gpuData from '../../data/gpus.json';
import {
  calculateDensity,
  getProfilesForGpu,
  getRecommendations,
} from '../../engines/densityEngine';
import { useConfigStore } from '../../store/configStore';
import type { GpuCard } from '../../types/gpu';

function generateConfigSnippet(gpu: GpuCard, selectedSeries: string[]): string {
  const filter =
    selectedSeries.length > 0
      ? (selectedSeries as ('Q' | 'B' | 'A' | 'C')[])
      : undefined;
  const profiles = getProfilesForGpu(gpu, filter);

  const lines = [
    `# Horizon graphic-profiles.properties for ${gpu.model}`,
    '# Generated by vGPU Advisor — https://fjacquet.github.io/vgpu-advisor/',
    '# Add these entries to: %SYSTEMDRIVE%\\ProgramData\\VMware\\VDM\\conf\\graphic-profiles.properties',
    '#',
    `# GPU: ${gpu.model} (${gpu.architecture}, ${gpu.vram_gb}GB, ${gpu.slot_width === 1 ? 'Single' : 'Double'}-Width)`,
    '',
    ...profiles.map((p) => `${p.horizonString}.name=${p.horizonString}`),
    '',
    '# Display capabilities per series:',
    '# Q (vWS): max 4 displays, 8K, 60fps — requires NVIDIA vWS license',
    '# B (vPC): max 2 displays, 45fps — requires NVIDIA vPC license',
    '# A (vCS): max 1 display, compute-optimized — requires NVIDIA vCS license',
    '# C (Compute): headless compute only — requires NVIDIA vCS license',
  ];

  return lines.join('\n');
}

export function PrintView() {
  const { t } = useTranslation();
  const {
    selectedGpuId,
    selectedSeries,
    pcieSlotsPerHost,
    gpuCountPerHost,
    hostCount,
    workloadType,
  } = useConfigStore();

  const gpus = gpuData as GpuCard[];
  const selectedGpu = gpus.find((g) => g.id === selectedGpuId);

  if (!selectedGpu) return null;

  const vramPerGpu = selectedGpu.vram_gb / selectedGpu.gpu_count_per_card;
  const seriesFilter = selectedSeries.length > 0 ? selectedSeries : undefined;
  const profiles = getProfilesForGpu(selectedGpu, seriesFilter);
  const recommendations = getRecommendations(
    selectedGpu,
    workloadType,
    pcieSlotsPerHost,
    hostCount
  );
  const configSnippet = generateConfigSnippet(selectedGpu, selectedSeries);
  const cardsPerHost = Math.floor(pcieSlotsPerHost / selectedGpu.slot_width);
  const gpusPerHost = cardsPerHost * selectedGpu.gpu_count_per_card;

  const RANK_LABELS = ['🥇 Best', '🥈 Runner-up', '🥉 Alternative'];

  return (
    <div
      className="print-only"
      style={{ fontFamily: 'sans-serif', padding: '2rem', color: '#111' }}
    >
      {/* Header */}
      <div className="print-section">
        <h1
          style={{
            fontSize: '1.5rem',
            fontWeight: 'bold',
            marginBottom: '0.25rem',
          }}
        >
          {t('app.title')}
        </h1>
        <p style={{ color: '#6b7280', marginBottom: '1rem' }}>
          {t('app.subtitle')}
        </p>
        <table
          style={{
            borderCollapse: 'collapse',
            width: '100%',
            fontSize: '0.875rem',
          }}
        >
          <tbody>
            <tr>
              <td
                style={{
                  padding: '4px 8px 4px 0',
                  fontWeight: 600,
                  width: '40%',
                }}
              >
                GPU
              </td>
              <td style={{ padding: '4px 0' }}>
                {selectedGpu.model} ({selectedGpu.architecture},{' '}
                {selectedGpu.vram_gb}GB)
              </td>
            </tr>
            <tr>
              <td style={{ padding: '4px 8px 4px 0', fontWeight: 600 }}>
                {t('deployment.pcieSlotsPerHost')}
              </td>
              <td style={{ padding: '4px 0' }}>{pcieSlotsPerHost}</td>
            </tr>
            <tr>
              <td style={{ padding: '4px 8px 4px 0', fontWeight: 600 }}>
                {t('density.cardsPerHost')}
              </td>
              <td style={{ padding: '4px 0' }}>{cardsPerHost}</td>
            </tr>
            <tr>
              <td style={{ padding: '4px 8px 4px 0', fontWeight: 600 }}>
                {t('density.gpusPerHost')}
              </td>
              <td style={{ padding: '4px 0' }}>{gpusPerHost}</td>
            </tr>
            <tr>
              <td style={{ padding: '4px 8px 4px 0', fontWeight: 600 }}>
                {t('deployment.hostCount')}
              </td>
              <td style={{ padding: '4px 0' }}>{hostCount}</td>
            </tr>
            <tr>
              <td style={{ padding: '4px 8px 4px 0', fontWeight: 600 }}>
                {t('deployment.workloadType')}
              </td>
              <td style={{ padding: '4px 0' }}>
                {t(`deployment.workloads.${workloadType}`)}
              </td>
            </tr>
            <tr>
              <td style={{ padding: '4px 8px 4px 0', fontWeight: 600 }}>
                Generated
              </td>
              <td style={{ padding: '4px 0' }}>
                {new Date().toISOString().split('T')[0]}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Profiles */}
      <div className="print-section">
        <h2
          style={{
            fontSize: '1.1rem',
            fontWeight: 'bold',
            marginBottom: '0.75rem',
          }}
        >
          {t('nav.profiles').toUpperCase()}
        </h2>
        <table
          style={{
            borderCollapse: 'collapse',
            width: '100%',
            fontSize: '0.8rem',
          }}
        >
          <thead>
            <tr style={{ background: '#f3f4f6' }}>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'left',
                  border: '1px solid #d1d5db',
                }}
              >
                Profile
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('profiles.vram')}
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('profiles.instances')}
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('profiles.displays')}
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('profiles.fps')}
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'left',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('profiles.license')}
              </th>
            </tr>
          </thead>
          <tbody>
            {profiles.map((profile) => (
              <tr key={profile.id}>
                <td
                  style={{
                    padding: '5px 8px',
                    border: '1px solid #e5e7eb',
                    fontFamily: 'monospace',
                  }}
                >
                  {profile.horizonString}
                </td>
                <td
                  style={{
                    padding: '5px 8px',
                    border: '1px solid #e5e7eb',
                    textAlign: 'right',
                  }}
                >
                  {profile.vram_gb}GB
                </td>
                <td
                  style={{
                    padding: '5px 8px',
                    border: '1px solid #e5e7eb',
                    textAlign: 'right',
                  }}
                >
                  {profile.maxInstances}
                </td>
                <td
                  style={{
                    padding: '5px 8px',
                    border: '1px solid #e5e7eb',
                    textAlign: 'right',
                  }}
                >
                  {profile.maxDisplays}
                </td>
                <td
                  style={{
                    padding: '5px 8px',
                    border: '1px solid #e5e7eb',
                    textAlign: 'right',
                  }}
                >
                  {profile.fps}
                </td>
                <td style={{ padding: '5px 8px', border: '1px solid #e5e7eb' }}>
                  {profile.license}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Density */}
      <div className="print-section">
        <h2
          style={{
            fontSize: '1.1rem',
            fontWeight: 'bold',
            marginBottom: '0.75rem',
          }}
        >
          {t('density.title').toUpperCase()}
        </h2>
        <table
          style={{
            borderCollapse: 'collapse',
            width: '100%',
            fontSize: '0.8rem',
          }}
        >
          <thead>
            <tr style={{ background: '#f3f4f6' }}>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'left',
                  border: '1px solid #d1d5db',
                }}
              >
                Profile
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('density.perGpu')}
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('density.perHost')}
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('density.perCluster')}
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('density.framebuffer')}
              </th>
            </tr>
          </thead>
          <tbody>
            {profiles.map((profile) => {
              const density = calculateDensity({
                profile,
                pcieSlotsPerHost,
                gpuCountPerHost,
                hostCount,
                slotWidth: selectedGpu.slot_width,
                gpuCountPerCard: selectedGpu.gpu_count_per_card,
                vramPerGpu,
              });
              const utilPct = Math.round(density.framebufferUtilization * 100);
              return (
                <tr key={profile.id}>
                  <td
                    style={{
                      padding: '5px 8px',
                      border: '1px solid #e5e7eb',
                      fontFamily: 'monospace',
                    }}
                  >
                    {profile.horizonString}
                  </td>
                  <td
                    style={{
                      padding: '5px 8px',
                      border: '1px solid #e5e7eb',
                      textAlign: 'right',
                    }}
                  >
                    {density.instancesPerGpu}
                  </td>
                  <td
                    style={{
                      padding: '5px 8px',
                      border: '1px solid #e5e7eb',
                      textAlign: 'right',
                    }}
                  >
                    {density.instancesPerHost}
                  </td>
                  <td
                    style={{
                      padding: '5px 8px',
                      border: '1px solid #e5e7eb',
                      textAlign: 'right',
                    }}
                  >
                    {density.instancesPerCluster}
                  </td>
                  <td
                    style={{
                      padding: '5px 8px',
                      border: '1px solid #e5e7eb',
                      textAlign: 'right',
                    }}
                  >
                    {utilPct}%
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Recommendations */}
      <div className="print-section">
        <h2
          style={{
            fontSize: '1.1rem',
            fontWeight: 'bold',
            marginBottom: '0.75rem',
          }}
        >
          {t('recommendations.title').toUpperCase()} —{' '}
          {t(`deployment.workloads.${workloadType}`)}
        </h2>
        <table
          style={{
            borderCollapse: 'collapse',
            width: '100%',
            fontSize: '0.8rem',
          }}
        >
          <thead>
            <tr style={{ background: '#f3f4f6' }}>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'left',
                  border: '1px solid #d1d5db',
                }}
              >
                Rank
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'left',
                  border: '1px solid #d1d5db',
                }}
              >
                Profile
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('density.perGpu')}
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('density.perHost')}
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'right',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('density.perCluster')}
              </th>
              <th
                style={{
                  padding: '6px 8px',
                  textAlign: 'left',
                  border: '1px solid #d1d5db',
                }}
              >
                {t('recommendations.reasoning')}
              </th>
            </tr>
          </thead>
          <tbody>
            {recommendations.map((rec, index) => (
              <tr key={rec.profile.id}>
                <td style={{ padding: '5px 8px', border: '1px solid #e5e7eb' }}>
                  {RANK_LABELS[index]}
                </td>
                <td
                  style={{
                    padding: '5px 8px',
                    border: '1px solid #e5e7eb',
                    fontFamily: 'monospace',
                  }}
                >
                  {rec.profile.horizonString}
                </td>
                <td
                  style={{
                    padding: '5px 8px',
                    border: '1px solid #e5e7eb',
                    textAlign: 'right',
                  }}
                >
                  {rec.densityResult.instancesPerGpu}
                </td>
                <td
                  style={{
                    padding: '5px 8px',
                    border: '1px solid #e5e7eb',
                    textAlign: 'right',
                  }}
                >
                  {rec.densityResult.instancesPerHost}
                </td>
                <td
                  style={{
                    padding: '5px 8px',
                    border: '1px solid #e5e7eb',
                    textAlign: 'right',
                  }}
                >
                  {rec.densityResult.instancesPerCluster}
                </td>
                <td
                  style={{
                    padding: '5px 8px',
                    border: '1px solid #e5e7eb',
                    fontSize: '0.75rem',
                  }}
                >
                  {rec.reasoning.map((r) => `✓ ${r}`).join(' · ')}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Config snippet */}
      <div className="print-section">
        <h2
          style={{
            fontSize: '1.1rem',
            fontWeight: 'bold',
            marginBottom: '0.75rem',
          }}
        >
          {t('config.title').toUpperCase()}
        </h2>
        <pre
          style={{
            fontSize: '0.7rem',
            fontFamily: 'monospace',
            background: '#f9fafb',
            border: '1px solid #d1d5db',
            borderRadius: '4px',
            padding: '1rem',
            whiteSpace: 'pre-wrap',
            wordBreak: 'break-all',
          }}
        >
          {configSnippet}
        </pre>
      </div>
    </div>
  );
}
